name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # invest about docker digest
    container: 
      image: node:18.12-alpine3.16
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release